name: Java CI with Gradle

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Export certification passphrase and prepare certificate
        env:
          SSL_CERT_PW: ${{ secrets.SSL_CERT_PW }}
          SSL_CERT_BASE64: ${{ secrets.SSL_CERT_BASE64 }}
        run: |
          echo "SSL_CERT_PW=$SSL_CERT_PW" >> $GITHUB_ENV
          echo "$SSL_CERT_BASE64" | base64 -d > certificate.p12
          echo "SSL_CERT_BASE64=./certificate.p12" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build
