# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21 
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Export certification passphrase and prepare certificate
      run: |
        export SSL_CERT_PW={{ secrets.SSL_CERT_PW }}
        echo "{{ secrets.SSL_CERT_BASE64 }}" | base64 -d > certificate.p12
        export SSL_CERT_BASE64=./certificate.p12
    - name: Export certification
      run:
    - name: Build with Gradle
      run: ./gradlew build
